### ISSUE TITLE
Not working with node 20.10 / npm 10.2 ?

### ISSUE THREAD

**Issue by ZalemCitizen** [kaldor/laravel-mix-clean#33]
Hello
Fresh install of node, laravel-mix 6

```
$ npm run watch

> watch
> mix watch

[webpack-cli] TypeError: Cannot redefine property: tap
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/var/www/.../node_modules/laravel-mix/src/helpers.js:5:8)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/var/www/.../node_modules/laravel-mix/src/index.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/var/www/.../node_modules/laravel-mix-clean/index.js:1:11)
```

webpack.mix.js (1st lines)
```
let mix = require('laravel-mix');
let productionSourceMaps = false;

const fs = require('fs');
const path = require('path');
const unzipper = require('unzipper');
const dayjs = require('dayjs');

const crypto = require('crypto');

require('shelljs/global');
require('laravel-mix-clean');
require('laravel-mix-wordpress-translate');
require('laravel-mix-copy-watched');
```

**Comment by ZalemCitizen** [comment]
Forget it I'm dumb ><
(installed modules in a wrong path)
